/**
 * ISO 3166-1 alpha-2 국가 코드
 * 가나다순 정렬
 */
export interface Country {
  code: string; // ISO 3166-1 alpha-2
  nameKo: string; // 한글 이름
  nameEn: string; // 영문 이름
}

export const COUNTRIES: Country[] = [
  { code: 'GH', nameKo: '가나', nameEn: 'Ghana' },
  { code: 'GA', nameKo: '가봉', nameEn: 'Gabon' },
  { code: 'GY', nameKo: '가이아나', nameEn: 'Guyana' },
  { code: 'GM', nameKo: '감비아', nameEn: 'Gambia' },
  { code: 'GP', nameKo: '과들루프', nameEn: 'Guadeloupe' },
  { code: 'GT', nameKo: '과테말라', nameEn: 'Guatemala' },
  { code: 'GU', nameKo: '괌', nameEn: 'Guam' },
  { code: 'GD', nameKo: '그레나다', nameEn: 'Grenada' },
  { code: 'GR', nameKo: '그리스', nameEn: 'Greece' },
  { code: 'GL', nameKo: '그린란드', nameEn: 'Greenland' },
  { code: 'GN', nameKo: '기니', nameEn: 'Guinea' },
  { code: 'GW', nameKo: '기니비사우', nameEn: 'Guinea-Bissau' },
  { code: 'NA', nameKo: '나미비아', nameEn: 'Namibia' },
  { code: 'NR', nameKo: '나우루', nameEn: 'Nauru' },
  { code: 'NG', nameKo: '나이지리아', nameEn: 'Nigeria' },
  { code: 'ZA', nameKo: '남아프리카공화국', nameEn: 'South Africa' },
  { code: 'NL', nameKo: '네덜란드', nameEn: 'Netherlands' },
  { code: 'NP', nameKo: '네팔', nameEn: 'Nepal' },
  { code: 'NO', nameKo: '노르웨이', nameEn: 'Norway' },
  { code: 'NZ', nameKo: '뉴질랜드', nameEn: 'New Zealand' },
  { code: 'NC', nameKo: '뉴칼레도니아', nameEn: 'New Caledonia' },
  { code: 'NE', nameKo: '니제르', nameEn: 'Niger' },
  { code: 'NI', nameKo: '니카라과', nameEn: 'Nicaragua' },
  { code: 'TW', nameKo: '대만', nameEn: 'Taiwan' },
  { code: 'DK', nameKo: '덴마크', nameEn: 'Denmark' },
  { code: 'DO', nameKo: '도미니카공화국', nameEn: 'Dominican Republic' },
  { code: 'DE', nameKo: '독일', nameEn: 'Germany' },
  { code: 'TL', nameKo: '동티모르', nameEn: 'East Timor' },
  { code: 'LA', nameKo: '라오스', nameEn: 'Laos' },
  { code: 'LR', nameKo: '라이베리아', nameEn: 'Liberia' },
  { code: 'LV', nameKo: '라트비아', nameEn: 'Latvia' },
  { code: 'RU', nameKo: '러시아', nameEn: 'Russia' },
  { code: 'LB', nameKo: '레바논', nameEn: 'Lebanon' },
  { code: 'LS', nameKo: '레소토', nameEn: 'Lesotho' },
  { code: 'RO', nameKo: '루마니아', nameEn: 'Romania' },
  { code: 'LU', nameKo: '룩셈부르크', nameEn: 'Luxembourg' },
  { code: 'RW', nameKo: '르완다', nameEn: 'Rwanda' },
  { code: 'LY', nameKo: '리비아', nameEn: 'Libya' },
  { code: 'LT', nameKo: '리투아니아', nameEn: 'Lithuania' },
  { code: 'LI', nameKo: '리히텐슈타인', nameEn: 'Liechtenstein' },
  { code: 'MG', nameKo: '마다가스카르', nameEn: 'Madagascar' },
  { code: 'MQ', nameKo: '마르티니크', nameEn: 'Martinique' },
  { code: 'MW', nameKo: '말라위', nameEn: 'Malawi' },
  { code: 'MY', nameKo: '말레이시아', nameEn: 'Malaysia' },
  { code: 'ML', nameKo: '말리', nameEn: 'Mali' },
  { code: 'MX', nameKo: '멕시코', nameEn: 'Mexico' },
  { code: 'MC', nameKo: '모나코', nameEn: 'Monaco' },
  { code: 'MA', nameKo: '모로코', nameEn: 'Morocco' },
  { code: 'MU', nameKo: '모리셔스', nameEn: 'Mauritius' },
  { code: 'MR', nameKo: '모리타니', nameEn: 'Mauritania' },
  { code: 'MZ', nameKo: '모잠비크', nameEn: 'Mozambique' },
  { code: 'ME', nameKo: '몬테네그로', nameEn: 'Montenegro' },
  { code: 'MD', nameKo: '몰도바', nameEn: 'Moldova' },
  { code: 'MV', nameKo: '몰디브', nameEn: 'Maldives' },
  { code: 'MT', nameKo: '몰타', nameEn: 'Malta' },
  { code: 'MN', nameKo: '몽골', nameEn: 'Mongolia' },
  { code: 'US', nameKo: '미국', nameEn: 'United States' },
  { code: 'MM', nameKo: '미얀마', nameEn: 'Myanmar' },
  { code: 'VU', nameKo: '바누아투', nameEn: 'Vanuatu' },
  { code: 'BH', nameKo: '바레인', nameEn: 'Bahrain' },
  { code: 'BB', nameKo: '바베이도스', nameEn: 'Barbados' },
  { code: 'VA', nameKo: '바티칸시국', nameEn: 'Vatican City' },
  { code: 'BS', nameKo: '바하마', nameEn: 'Bahamas' },
  { code: 'BD', nameKo: '방글라데시', nameEn: 'Bangladesh' },
  { code: 'BM', nameKo: '버뮤다', nameEn: 'Bermuda' },
  { code: 'BJ', nameKo: '베냉', nameEn: 'Benin' },
  { code: 'VE', nameKo: '베네수엘라', nameEn: 'Venezuela' },
  { code: 'VN', nameKo: '베트남', nameEn: 'Vietnam' },
  { code: 'BE', nameKo: '벨기에', nameEn: 'Belgium' },
  { code: 'BY', nameKo: '벨라루스', nameEn: 'Belarus' },
  { code: 'BZ', nameKo: '벨리즈', nameEn: 'Belize' },
  { code: 'BA', nameKo: '보스니아헤르체고비나', nameEn: 'Bosnia and Herzegovina' },
  { code: 'BW', nameKo: '보츠와나', nameEn: 'Botswana' },
  { code: 'BO', nameKo: '볼리비아', nameEn: 'Bolivia' },
  { code: 'BI', nameKo: '부룬디', nameEn: 'Burundi' },
  { code: 'BF', nameKo: '부르키나파소', nameEn: 'Burkina Faso' },
  { code: 'BT', nameKo: '부탄', nameEn: 'Bhutan' },
  { code: 'BG', nameKo: '불가리아', nameEn: 'Bulgaria' },
  { code: 'BR', nameKo: '브라질', nameEn: 'Brazil' },
  { code: 'BN', nameKo: '브루나이', nameEn: 'Brunei' },
  { code: 'WS', nameKo: '사모아', nameEn: 'Samoa' },
  { code: 'SA', nameKo: '사우디아라비아', nameEn: 'Saudi Arabia' },
  { code: 'CY', nameKo: '사이프러스', nameEn: 'Cyprus' },
  { code: 'SM', nameKo: '산마리노', nameEn: 'San Marino' },
  { code: 'ST', nameKo: '상투메프린시페', nameEn: 'Sao Tome and Principe' },
  { code: 'SN', nameKo: '세네갈', nameEn: 'Senegal' },
  { code: 'RS', nameKo: '세르비아', nameEn: 'Serbia' },
  { code: 'SC', nameKo: '세이셸', nameEn: 'Seychelles' },
  { code: 'LC', nameKo: '세인트루시아', nameEn: 'Saint Lucia' },
  { code: 'VC', nameKo: '세인트빈센트그레나딘', nameEn: 'Saint Vincent and the Grenadines' },
  { code: 'KN', nameKo: '세인트키츠네비스', nameEn: 'Saint Kitts and Nevis' },
  { code: 'SO', nameKo: '소말리아', nameEn: 'Somalia' },
  { code: 'SB', nameKo: '솔로몬제도', nameEn: 'Solomon Islands' },
  { code: 'SD', nameKo: '수단', nameEn: 'Sudan' },
  { code: 'SR', nameKo: '수리남', nameEn: 'Suriname' },
  { code: 'LK', nameKo: '스리랑카', nameEn: 'Sri Lanka' },
  { code: 'SZ', nameKo: '스와질란드', nameEn: 'Swaziland' },
  { code: 'SE', nameKo: '스웨덴', nameEn: 'Sweden' },
  { code: 'CH', nameKo: '스위스', nameEn: 'Switzerland' },
  { code: 'ES', nameKo: '스페인', nameEn: 'Spain' },
  { code: 'SK', nameKo: '슬로바키아', nameEn: 'Slovakia' },
  { code: 'SI', nameKo: '슬로베니아', nameEn: 'Slovenia' },
  { code: 'SY', nameKo: '시리아', nameEn: 'Syria' },
  { code: 'SL', nameKo: '시에라리온', nameEn: 'Sierra Leone' },
  { code: 'SG', nameKo: '싱가포르', nameEn: 'Singapore' },
  { code: 'AE', nameKo: '아랍에미리트', nameEn: 'United Arab Emirates' },
  { code: 'AW', nameKo: '아루바', nameEn: 'Aruba' },
  { code: 'AM', nameKo: '아르메니아', nameEn: 'Armenia' },
  { code: 'AR', nameKo: '아르헨티나', nameEn: 'Argentina' },
  { code: 'IS', nameKo: '아이슬란드', nameEn: 'Iceland' },
  { code: 'HT', nameKo: '아이티', nameEn: 'Haiti' },
  { code: 'IE', nameKo: '아일랜드', nameEn: 'Ireland' },
  { code: 'AZ', nameKo: '아제르바이잔', nameEn: 'Azerbaijan' },
  { code: 'AF', nameKo: '아프가니스탄', nameEn: 'Afghanistan' },
  { code: 'AD', nameKo: '안도라', nameEn: 'Andorra' },
  { code: 'AL', nameKo: '알바니아', nameEn: 'Albania' },
  { code: 'DZ', nameKo: '알제리', nameEn: 'Algeria' },
  { code: 'AO', nameKo: '앙골라', nameEn: 'Angola' },
  { code: 'AG', nameKo: '앤티가바부다', nameEn: 'Antigua and Barbuda' },
  { code: 'ER', nameKo: '에리트레아', nameEn: 'Eritrea' },
  { code: 'EE', nameKo: '에스토니아', nameEn: 'Estonia' },
  { code: 'EC', nameKo: '에콰도르', nameEn: 'Ecuador' },
  { code: 'ET', nameKo: '에티오피아', nameEn: 'Ethiopia' },
  { code: 'SV', nameKo: '엘살바도르', nameEn: 'El Salvador' },
  { code: 'GB', nameKo: '영국', nameEn: 'United Kingdom' },
  { code: 'YE', nameKo: '예멘', nameEn: 'Yemen' },
  { code: 'OM', nameKo: '오만', nameEn: 'Oman' },
  { code: 'AT', nameKo: '오스트리아', nameEn: 'Austria' },
  { code: 'AU', nameKo: '오스트레일리아', nameEn: 'Australia' },
  { code: 'HN', nameKo: '온두라스', nameEn: 'Honduras' },
  { code: 'JO', nameKo: '요르단', nameEn: 'Jordan' },
  { code: 'UG', nameKo: '우간다', nameEn: 'Uganda' },
  { code: 'UY', nameKo: '우루과이', nameEn: 'Uruguay' },
  { code: 'UZ', nameKo: '우즈베키스탄', nameEn: 'Uzbekistan' },
  { code: 'UA', nameKo: '우크라이나', nameEn: 'Ukraine' },
  { code: 'IQ', nameKo: '이라크', nameEn: 'Iraq' },
  { code: 'IR', nameKo: '이란', nameEn: 'Iran' },
  { code: 'IL', nameKo: '이스라엘', nameEn: 'Israel' },
  { code: 'EG', nameKo: '이집트', nameEn: 'Egypt' },
  { code: 'IT', nameKo: '이탈리아', nameEn: 'Italy' },
  { code: 'IN', nameKo: '인도', nameEn: 'India' },
  { code: 'ID', nameKo: '인도네시아', nameEn: 'Indonesia' },
  { code: 'JP', nameKo: '일본', nameEn: 'Japan' },
  { code: 'JM', nameKo: '자메이카', nameEn: 'Jamaica' },
  { code: 'ZM', nameKo: '잠비아', nameEn: 'Zambia' },
  { code: 'GQ', nameKo: '적도기니', nameEn: 'Equatorial Guinea' },
  { code: 'GE', nameKo: '조지아', nameEn: 'Georgia' },
  { code: 'CN', nameKo: '중국', nameEn: 'China' },
  { code: 'CF', nameKo: '중앙아프리카공화국', nameEn: 'Central African Republic' },
  { code: 'DJ', nameKo: '지부티', nameEn: 'Djibouti' },
  { code: 'ZW', nameKo: '짐바브웨', nameEn: 'Zimbabwe' },
  { code: 'TD', nameKo: '차드', nameEn: 'Chad' },
  { code: 'CZ', nameKo: '체코', nameEn: 'Czech Republic' },
  { code: 'CL', nameKo: '칠레', nameEn: 'Chile' },
  { code: 'CM', nameKo: '카메룬', nameEn: 'Cameroon' },
  { code: 'CV', nameKo: '카보베르데', nameEn: 'Cape Verde' },
  { code: 'KZ', nameKo: '카자흐스탄', nameEn: 'Kazakhstan' },
  { code: 'QA', nameKo: '카타르', nameEn: 'Qatar' },
  { code: 'KH', nameKo: '캄보디아', nameEn: 'Cambodia' },
  { code: 'CA', nameKo: '캐나다', nameEn: 'Canada' },
  { code: 'KE', nameKo: '케냐', nameEn: 'Kenya' },
  { code: 'KM', nameKo: '코모로', nameEn: 'Comoros' },
  { code: 'CR', nameKo: '코스타리카', nameEn: 'Costa Rica' },
  { code: 'CI', nameKo: '코트디부아르', nameEn: 'Ivory Coast' },
  { code: 'CO', nameKo: '콜롬비아', nameEn: 'Colombia' },
  { code: 'CG', nameKo: '콩고', nameEn: 'Congo' },
  { code: 'CD', nameKo: '콩고민주공화국', nameEn: 'Democratic Republic of the Congo' },
  { code: 'CU', nameKo: '쿠바', nameEn: 'Cuba' },
  { code: 'KW', nameKo: '쿠웨이트', nameEn: 'Kuwait' },
  { code: 'HR', nameKo: '크로아티아', nameEn: 'Croatia' },
  { code: 'KG', nameKo: '키르기스스탄', nameEn: 'Kyrgyzstan' },
  { code: 'KI', nameKo: '키리바시', nameEn: 'Kiribati' },
  { code: 'TH', nameKo: '태국', nameEn: 'Thailand' },
  { code: 'TJ', nameKo: '타지키스탄', nameEn: 'Tajikistan' },
  { code: 'TZ', nameKo: '탄자니아', nameEn: 'Tanzania' },
  { code: 'TR', nameKo: '튀르키예', nameEn: 'Turkey' },
  { code: 'TG', nameKo: '토고', nameEn: 'Togo' },
  { code: 'TO', nameKo: '통가', nameEn: 'Tonga' },
  { code: 'TM', nameKo: '투르크메니스탄', nameEn: 'Turkmenistan' },
  { code: 'TV', nameKo: '투발루', nameEn: 'Tuvalu' },
  { code: 'TN', nameKo: '튀니지', nameEn: 'Tunisia' },
  { code: 'TT', nameKo: '트리니다드토바고', nameEn: 'Trinidad and Tobago' },
  { code: 'PA', nameKo: '파나마', nameEn: 'Panama' },
  { code: 'PY', nameKo: '파라과이', nameEn: 'Paraguay' },
  { code: 'PK', nameKo: '파키스탄', nameEn: 'Pakistan' },
  { code: 'PG', nameKo: '파푸아뉴기니', nameEn: 'Papua New Guinea' },
  { code: 'PW', nameKo: '팔라우', nameEn: 'Palau' },
  { code: 'PS', nameKo: '팔레스타인', nameEn: 'Palestine' },
  { code: 'PE', nameKo: '페루', nameEn: 'Peru' },
  { code: 'PT', nameKo: '포르투갈', nameEn: 'Portugal' },
  { code: 'PL', nameKo: '폴란드', nameEn: 'Poland' },
  { code: 'FR', nameKo: '프랑스', nameEn: 'France' },
  { code: 'FJ', nameKo: '피지', nameEn: 'Fiji' },
  { code: 'FI', nameKo: '핀란드', nameEn: 'Finland' },
  { code: 'PH', nameKo: '필리핀', nameEn: 'Philippines' },
  { code: 'HU', nameKo: '헝가리', nameEn: 'Hungary' },
  { code: 'HK', nameKo: '홍콩', nameEn: 'Hong Kong' },
];

/**
 * 국가 코드로 국가 찾기
 */
export function findCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((country) => country.code === code);
}

/**
 * 국가명(한글)으로 국가 찾기
 */
export function findCountryByName(nameKo: string): Country | undefined {
  return COUNTRIES.find((country) => country.nameKo === nameKo);
}
